apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-mmph
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-mmph
    app.kubernetes.io/part-of: tkrw-pr714-0075-0017-app
  name: devfile-sample-mmph
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-mmph
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-mmph
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0017-tenant/tkrw-pr714-0075-0017-app/devfile-sample-mmph@sha256:45bcd9eb1679aaa9467326f28349f5cd4a68d7cc10ea2d60ee48ec9c3cff2522
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
